# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MovieApp' do
    
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!
    
    pod 'Alamofire'
    pod 'SwiftyJSON'

end

target 'MovieAppTests' do

end

target 'MovieAppUITests' do

end

